{
  pkgs,
  lib,
  unifiedAdditionalPackages,
  engine ? "lualatex",
  emitRc ? true,
}: let
  # Create unified TeX Live environment with all packages (including base packages)
  unifiedTexPackages =
    {
      inherit
        (pkgs.texlive)
        latex-bin
        latexmk
        latexindent
        biblatex
        biber
        csquotes
        luaotfload
        fontspec
        lm
        cm
        ec
        tex-gyre
        ;
      scheme = pkgs.texlive.scheme-basic;
    }
    // unifiedAdditionalPackages;

  unifiedTexEnv = pkgs.texlive.combine unifiedTexPackages;

  # Wrap ltex-ls to only see the unified TeX Live binaries
  ltexLsWrapped = pkgs.writeShellScriptBin "ltex-ls" ''
    export PATH=${lib.makeBinPath [unifiedTexEnv]}
    exec ${pkgs.ltex-ls}/bin/ltex-ls "\$@"
  '';

  # Create packages for the unified TeX Live environment and latexmk
  # Always create these if we have module-level packages, even without documents
  unifiedPackages = {
    texlive = unifiedTexEnv;
    latexmk = pkgs.writeShellScriptBin "latexmk" ''
      exec ${lib.getExe' unifiedTexEnv "latexmk"} "\$@"
    '';
    latexindent = pkgs.writeShellScriptBin "latexindent" ''
      exec ${lib.getExe' unifiedTexEnv "latexindent"} "\$@"
    '';
  };

  # Emit a .latexmkrc matching engine and out-dir
  latexmkrcText = ''
    # Auto-generated by latex-utils
    # Engine
    $pdf_mode = 1;
    $pdflatex = '${lib.getExe' unifiedTexEnv engine} -interaction=nonstopmode -file-line-error -synctex=1 %O %S';
    $lualatex = '${lib.getExe' unifiedTexEnv "lualatex"} -interaction=nonstopmode -file-line-error -synctex=1 %O %S';
    $xelatex = '${lib.getExe' unifiedTexEnv "xelatex"} -interaction=nonstopmode -file-line-error -synctex=1 %O %S';
    $bibtex = '${lib.getExe' unifiedTexEnv "bibtex"} %O';
    $biber = '${lib.getExe' unifiedTexEnv "biber"} %O %B';

    # Unified out-dir for IDEs
    $out_dir = '.latex-build';

    # SyncTeX and non-stop interaction defaults for latex (non-pdf mode)
    $synctex = 1;
    $latex = "$latex -interaction=nonstopmode -file-line-error";
  '';

  latexmkrcPackage = pkgs.writeTextFile {
    name = "latexmkrc";
    destination = "/.latexmkrc";
    text = latexmkrcText;
  };

  # Helper dev shell fragment (no VS Code integration)
  unifiedTexShell = pkgs.mkShell {
    buildInputs = [unifiedTexEnv ltexLsWrapped] ++ lib.optional emitRc latexmkrcPackage;
    shellHook = ''
      ${lib.optionalString emitRc ''ln -sf "${latexmkrcPackage}/.latexmkrc" .latexmkrc''}
      if [ -z "${"''${LATEX_UTILS_UNIFIED_READY:-}"}" ]; then
        export LATEX_UTILS_UNIFIED_READY=1
        echo 'Unified TeX Live environment ready.'
      fi
    '';
  };

  # Thin latexmk wrapper
  latexmkWrapper = pkgs.writeShellScriptBin "latexmk" ''
    exec ${lib.getExe' unifiedTexEnv "latexmk"} "\$@"
  '';
in {
  inherit
    unifiedTexEnv
    ltexLsWrapped
    unifiedPackages
    unifiedTexShell
    latexmkWrapper
    latexmkrcPackage
    ;
}
