{
  pkgs,
  lib,
  ...
}: {
  # Normalizes extraTexPackages to an attrset of derivations
  #
  # This function handles the complexity of TeX Live package structure in nixpkgs
  # and provides a unified interface for specifying additional TeX packages.
  #
  # TeX Live Package Structure in Nixpkgs:
  # =====================================
  #
  # IMPORTANT: This implementation supports the NEW TeX Live package structure
  # introduced in nixpkgs in spring 2024 (commit 9daed7b). If you're using
  # older nixpkgs (nixos-23.11, nixos-24.05 early versions), please update
  # to a recent nixpkgs-unstable or nixos-24.11+.
  #
  # There have been two distinct "eras" of TeX Live packages in nixpkgs:
  #
  # ## Legacy Era (2019-2024, unsupported):
  # pkgs.texlive.amsfonts = {
  #   pname = "amsfonts";
  #   tlType = "run";
  #   out = «derivation»;
  #   doc = «derivation»;
  #   source = «derivation»;
  # }
  # - Direct access to outputs as top-level attributes
  # - tlType and pname on the wrapper itself
  # - lib.isDerivation on wrapper: false, but true on outputs
  #
  # ## Current Era (2024+, supported):
  # There are three main "shapes" of TeX Live objects in modern nixpkgs:
  #
  # 1. Individual TeX Live Package (wrapper attrset):
  #    pkgs.texlive.amsfonts = {
  #      pkgs = [
  #        «derivation with tlType="run", pname="amsfonts"»,
  #        «derivation with tlType="doc", pname="amsfonts"»,
  #        «derivation with tlType="source", pname="amsfonts"»
  #      ];
  #      meta = { description = ...; };
  #    }
  #    - lib.isDerivation: false (it's just an attrset wrapper)
  #    - Contains actual derivations in the 'pkgs' list
  #    - Each derivation has TeX Live metadata (tlType, pname, outputs, etc.)
  #    - This is what you get when you reference pkgs.texlive.packagename
  #
  # 2. Individual Derivations (inside the packages):
  #    (builtins.head pkgs.texlive.amsfonts.pkgs) = {
  #      tlType = "run";     # or "doc", "source", "bin"
  #      pname = "amsfonts";
  #      outputs = ["out"];
  #      # ... standard derivation attributes (drvPath, outPath, etc.)
  #    }
  #    - lib.isDerivation: true
  #    - Has TeX Live metadata (tlType, etc.)
  #    - These are the actual buildable units
  #    - Generated by buildTexLivePackage
  #
  # 3. Combined TeX Live Environment:
  #    texlive.combine { inherit (texlive) amsfonts xcolor; } = {
  #      pname = "texlive-combined";
  #      out = «derivation»;
  #      texlivePackages = [ ... ]; # Reference to original packages
  #      # ... other outputs and metadata
  #    }
  #    - lib.isDerivation: true
  #    - Result of buildEnv combining multiple packages
  #    - Has a texlivePackages attribute listing the original packages
  #    - This is what you use as a buildInput in other derivations
  #
  # Accepted Input Types:
  # ====================
  # - List of strings (package names from pkgs.texlive): ["amsmath" "xcolor"]
  # - List of derivations: [some-custom-derivation another-derivation]
  # - List of TeX Live package objects: [pkgs.texlive.amsfonts pkgs.texlive.xcolor]
  # - Function returning any of the above: (discovered: [pkgs.texlive.amsfonts])
  #
  # Output:
  # =======
  # Always returns an attrset where:
  # - Keys are package names (extracted from pname or derived)
  # - Values are the original objects (derivations or TeX Live package wrappers)
  # - This format is compatible with texlive.combine and other TeX Live tools
  normalizeExtraTexPackages = {
    extraTexPackages,
    discoveredPackages,
  }:
    with lib; let
      # Predicate for detecting TeX Live package wrapper objects (2024+ era)
      # These are the attrsets returned by buildTexLivePackage that contain
      # a 'pkgs' list with the actual derivations.
      isTexLivePackage = obj:
        (builtins.isAttrs obj)
        && (obj ? pkgs)
        && (builtins.isList obj.pkgs)
        && (obj.pkgs
          == []
          || (
            lib.isDerivation (builtins.head obj.pkgs)
            && (builtins.head obj.pkgs) ? tlType
          ));

      # Helper to convert list of strings to derivations
      # Strings are looked up in pkgs.texlive.*
      stringsToDerivations = strings:
        builtins.listToAttrs (
          map (item: {
            name = item;
            value = pkgs.texlive.${item};
          })
          strings
        );

      # Helper to convert list of derivations to attrset
      # Uses pname if available, otherwise generates a name
      derivationsToAttrset = derivations:
        builtins.listToAttrs (
          lib.lists.imap0 (i: drv: {
            name = drv.pname or "custom-package-${toString i}";
            value = drv;
          })
          derivations
        );

      # Helper to convert list of TeX Live package objects to attrset
      # Extracts meaningful names from the package metadata
      texLivePackagesToAttrset = packages:
        builtins.listToAttrs (
          lib.lists.imap0 (i: pkg: let
            # Extract a meaningful name from the TeX Live package
            # Try multiple strategies to get the best name possible
            name =
              # Strategy 1: Use pname from wrapper (if available)
              if pkg ? pname
              then pkg.pname
              # Strategy 2: Extract pname from first derivation in pkgs list
              else if pkg ? pkgs && pkg.pkgs != [] && ((builtins.head pkg.pkgs) ? pname)
              then (builtins.head pkg.pkgs).pname
              # Strategy 3: Extract name from first derivation and parse it
              else if pkg ? pkgs && pkg.pkgs != [] && ((builtins.head pkg.pkgs) ? name)
              then let
                fullName = (builtins.head pkg.pkgs).name;
                # Extract just the package name part (before version)
                nameParts = lib.strings.splitString "-" fullName;
              in
                if builtins.length nameParts > 0
                then builtins.head nameParts
                else "texlive-package-${toString i}"
              # Strategy 4: Fallback to generic name
              else "texlive-package-${toString i}";
          in {
            inherit name;
            value = pkg;
          })
          packages
        );

      # Safe string representation for error messages.
      # toString crashes on attrsets ("cannot coerce a set to a string") with
      # an uncatchable type error, so we use typeOf + truncated JSON instead.
      safeDescribe = val:
        if builtins.isAttrs val
        then let
          json = builtins.toJSON val;
          preview = builtins.substring 0 100 json;
          ellipsis =
            if builtins.stringLength json > 100
            then "..."
            else "";
        in "attrset: ${preview}${ellipsis}"
        else if builtins.isList val
        then "list(${toString (builtins.length val)} items)"
        else if builtins.isFunction val
        then "function"
        else toString val;

      # Helper to determine what type of list we have and convert appropriately
      # This implements the homogeneous type checking mentioned in the analysis
      convertList = items:
        if items == []
        then {}
        else if lib.isString (builtins.head items)
        then
          # List of strings - verify all are strings
          if builtins.all lib.isString items
          then stringsToDerivations items
          else throw "extraTexPackages list must be homogeneous: all strings, all derivations, or all TeX Live package objects"
        else if lib.isDerivation (builtins.head items)
        then
          # List of derivations - verify all are derivations
          if builtins.all lib.isDerivation items
          then derivationsToAttrset items
          else throw "extraTexPackages list must be homogeneous: all strings, all derivations, or all TeX Live package objects. Got list starting with derivation, but found non-derivation."
        else if isTexLivePackage (builtins.head items)
        then
          # List of TeX Live package objects - verify all are TeX Live packages
          if builtins.all isTexLivePackage items
          then texLivePackagesToAttrset items
          else throw "extraTexPackages list must be homogeneous: all strings, all derivations, or all TeX Live package objects. Got list starting with TeX Live package object, but found non-TeX Live package object."
        else
          # Check if this might be a legacy TeX Live package and provide helpful error
          let
            firstItem = builtins.head items;
            isLegacyTexLivePackage =
              builtins.isAttrs firstItem
              && firstItem ? tlType
              && firstItem ? out
              && lib.isDerivation firstItem.out;
          in
            if isLegacyTexLivePackage
            then
              throw ''
                extraTexPackages contains legacy TeX Live package objects (pre-2024 format).
                This version of latex-utils requires the modern TeX Live package structure.

                Please update to a recent nixpkgs version (nixpkgs-unstable or nixos-24.11+) to get
                the modern TeX Live packages, or use an older version of latex-utils.

                To check your nixpkgs version:
                nix eval --impure --expr 'with import <nixpkgs> {}; builtins.hasAttr "pkgs" texlive.amsfonts'
                Should return: true (modern) or false (legacy)
              ''
            else throw "extraTexPackages list items must be strings, derivations, or TeX Live package objects, got: ${builtins.typeOf firstItem} for the first item (${safeDescribe firstItem})";
    in
      if lib.isList extraTexPackages
      then convertList extraTexPackages
      else if lib.isFunction extraTexPackages
      then
        # Handle function returning list of derivations or TeX Live package objects
        # Functions are called with discoveredPackages and must return a list
        let
          result = extraTexPackages discoveredPackages;
        in
          if lib.isList result
          then convertList result
          else throw "extraTexPackages was a function, but it did not return a list. Instead, it returned a ${builtins.typeOf result} (${safeDescribe result})"
      else throw "extraTexPackages must be a list or function, but it is a ${builtins.typeOf extraTexPackages} (${safeDescribe extraTexPackages})";
}
