site_name: latex-utils
repo_url: https://github.com/jmmaloney4/latex-utils
docs_dir: .
nav:
  - Home: index.md
  - User Guide:
      - Development Shells: user/devshells.md
      - IDE Integration: user/ide-integration.md
      - TeX Live Integration: user/texlive-integration.md
      - Library Reference: user/library.md
      - Unit Testing: user/unit-testing.md
      - Consumer Flake Example: user/consumer-flake-example.md
      - Example Module Packages: user/example-module-packages.nix
      - Comprehensive Example: user/comprehensive-example.nix
