name: nix flake update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00
permissions:
  contents: write
  pull-requests: write
jobs:
  nix-flake-update:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@b67ad2f0e8376a0bc947db191e4484285b6f5b56 # main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@01467157fe94fd33c160f7311a78689ceaad3ec4 # main
        with:
          branch: nix-flake-update
          commit-msg: nix flake update
          pr-title: "nix flake update"
          pr-assignees: jmmaloney4
