name: '❄️ nix'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  packages: write
jobs:
  nix:
    uses: jmmaloney4/toolbox/.github/workflows/nix.yml@main
    with:
      runs-on: self-hosted
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
