name: 📌 add to project
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
permissions:
  contents: read
jobs:
  add-to-project:
    uses: jmmaloney4/sector7/.github/workflows/add-to-project.yml@f20ef2a959307d732e59550fb0e8df15374c07cd # main
    with:
      runs-on: self-hosted
